FROM python:3.8-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt /app/requirements.txt
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Copy all necessary files
COPY . /app

# Expose port for the API
EXPOSE 5000

# Run the main application
# CMD ["python", "train.py"]
CMD ["python", "log_model_sentiment.py"]