name: MLflow CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute mlflow_model_management.ipynb

      - name: Log in to Dagshub
        run: |
          dvc remote modify --local dagshub --auth basic
          dvc remote modify --local dagshub.user ${{ secrets.DAGSHUB_USER }}
          dvc remote modify --local dagshub.password ${{ secrets.DAGSHUB_PASSWORD }}

      - name: Track and register models in MLflow
        run: |
          python track_and_register.py

      - name: Deploy model
        run: |
          python deploy_model.py
