name: CI/CD for Sentiment Model

on:
  [push]
  # workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t valiantsr/sentiment-model:latest sentiment_analysis/.
          docker push valiantsr/sentiment-model:latest

      - name: Training Model
        run: docker run --rm valiantsr/sentiment-model:latest python train.py

      - name: Run Tests
        run: docker run --rm valiantsr/sentiment-model:latest python test.py

      - name: Retrain Model
        run: docker run --rm valiantsr/sentiment-model:latest python retrain.py

      - name: Test API
        run: |
          docker run -d --name sentiment-api -p 5000:5000 valiantsr/sentiment-model:latest
          sleep 10
          curl -X POST http://localhost:5000/predict -H "Content-Type: application/json" -d '{"text": "Your test text here"}'

      # - name: Log model
      #   run: docker run --rm valiantsr/sentiment-model:latest python log_model_sentiment.py

      # - name: Retrain model
      #   run: docker run --rm valiantsr/sentiment-model:latest python retrain_model_sentiment.py

      # - name: Test model
      #   run: docker run --rm valiantsr/sentiment-model:latest python test_model_sentiment.py

      # 3 jobs diatas digunakan untuk percobaan load model sentiment yang sudah dibuat di device lain
