# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - "sentiment_analysis/**"
#   pull_request:
#     branches:
#       - main
#     paths:
#       - "sentiment_analysis/**"

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.8

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r sentiment_analysis/requirements.txt

#       - name: Log model
#         run: |
#           python sentiment_analysis/log_model_sentiment.py

#       - name: Retrain model
#         run: |
#           python sentiment_analysis/retrain_model_sentiment.py

#       - name: Test model
#         run: |
#           python sentiment_analysis/test_model_sentiment.py

name: CI/CD for Sentiment Model

on: [push]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t valiantsr/sentimet-model:latest .
          docker push valiantsr/sentimet-model:latest

      - name: Run Tests
        run: docker run --rm valiantsr/sentimet-model:latest python test_model_sentiment.py
